sudo: required

services:
  - docker

branches:
  only:
    - master
    - development

env:
    global:
        - DOCKER_VERSION=1.11.2-0~trusty
        - DOCKER_COMPOSE_VERSION=1.8.0-rc1
        - SERVICE=backend

        # DOCKER_USERNAME
        - secure: "v6eRHn17NWhNlaC5xRTOPSVbUt0bOEX26zsMquiCo2cL+QiwU0fZdFXENjpRk9qvOb3psmeYTG03POAy72M7wdofYukyf5gxPTDjFL1FoHVmi+ZPDD7THKycFtR+Yb6vMCevKU/pFdC42yXyJpxvk3JLCWqGjYaAYiuhG1VbE+g4Vv6T+YJ+JgdIzNkZSFdIleFj5PQNZV90TcLMdyouRcUb0Ua9pLD4pJbPM3rgmcs7jeDkb2rIFQOTSXjodhUgeOc/60v4XezvwB7ylqy4FHfxjriJCrz9iu9Tg8eABhe7NoQAsjuuoOXYG+9/rfpiGiL2CaRkXuavBJ5jE+gl8UxHL8QbVj6CVrbv/GZQCciUT8xwcEGQE5LlP5PTiZ1eTEbLienOyiXtv+xd5dgF7bPW7XXLDEnGIZljsGjpMn1MExe/QNWqs4UY40XXXPWKHhqgKeL79c7+spT5uSb3OuwFCdLz6k1G/H4VFHLHD1vaXFT038FmFYtrM2DVC40KfOT6b6jQb9oW2qsYluxXwWY1psaJ3GGDsWsqRym55qQNy/nsqhfuy6bMBaY9G96h088YfTsZP+TkuAqB7jJgNxV+UCOfyXhdiJCWTKO+RtmMZl+Hq7oDPAQ4HUW4aXKIzULIZ1YL7GT16lVHg6SW4k57JTnPo6wIm1S5DNlE5IQ="

        # DOCKER_PASS
        - secure: "mwRlUvzNpfwHWna3dtSxUE+a+IPwsvAexDfcN8EOGRWMUPMoWlX0M677tshpsBkwldMRq2ShzY6j2E/fMKg1GjW026i8lTN7RVBw02XS82FbKe/M2krPio0Zg8bWxBGxsyczlDOCWy7ka4m7EgTW3QyZN2ztcMtT8Yj3NMVjC6j10u2qfMHWRit53/6Mh4A4mdWURJpTw+XLK+NPeAkzzZgmNdQbVEoe8zi+PirbzRG2uRc5HSArKs/Jt39Ns4o5xUCBgUfaX22D2y65aWTsZRKNadzu2dE+11i2GA2uHFbSHQyY32ir/U5KdpQj3Lg2jKZ5zIyQiSDsp1xS1sW0QeZbKl+ex8DsZwqEsUtLXHTJ5F0ObxdLc6FDkVQNZML3MD7jnCU8dcy64jxlL3A9AxBu/xrc46HAUOPQ8e8LgotyIlH7yw+yn135TK3ZTaz1CNpVRXm/A9Shqbo3vNH0u1/5Q6D0CY+cWf9LIYoSVo0iheD437YnSmW/5ZyY1BVX1PTepPUmCwp4K8ja2tOaf3w9N8NEwb57IEXOqEMrGuA1M/sHnWQroRPjl9KQem/MRQ7PfMoQS60oZOuVYMFtqAA8pdfy8M6FroF1b5o/2NOyzbbwiCiG7lZZzTsnqUV+e45FCYm9TXycFJr0ykjOyyUSu/romvxKja0tWONGRbk="

after_success: test "$TRAVIS_PULL_REQUEST" == "false" && ./useful/after_success.sh "$DOCKER_USER" "$DOCKER_PASS" "$SERVICE" "$TRAVIS_BRANCH"

before_install:
  # Clone 'deluge' project
  - git clone --recursive https://github.com/absortium/deluge.git
  - pushd deluge

  # Create mock '.sensitive'
  - ./useful/create_mock_sensitive.sh

  # List 'docker-engine' versions
  - apt-cache madison docker-engine

  # Upgrade 'docker-engine' to specific version
  - ./useful/upgrade_docker_engine.sh

  # Upgrade 'docker-compose' to specific version
  - ./useful/upgrade_docker_compose.sh

  # Check 'docker' and 'docker-compose' versions
  - docker version
  - docker-compose version

script:
  - ./useful/install.sh "$SERVICE" "$TRAVIS_BRANCH" "$TRAVIS"