sudo: required

services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.11.2-1
        - DOCKER_COMPOSE_VERSION=1.8.0-rc1
        - SERVICE=backend

before_install:
  # Clone `deluge` project
  - git clone --recursive https://github.com/absortium/deluge.git
  - pushd deluge

  # Create mock '.sensitive' file
  - ./useful/create_mock_sensitive.sh

  # Upgrade docker-engine to specific version
  - ./useful/upgrade_docker_engine.sh

  # Upgrade docker-compose to specific version
  - ./useful/upgrade_docker_compose.sh

  # Check docker and docker-compose versions
  - docker version
  - docker-compose version

  # Checkout and pull changes of `backend` service.
  - pushd services/$SERVICE
  - git checkout $TRAVIS_BRANCH
  - git pull
  - popd

script:
  - ./useful/install.sh $SERVICE