__author__ = 'andrew.shvv@gmail.com'

from absortium.utils import convert

SELL = 0
BUY = 1
AVAILABLE_ORDER_TYPES = {
    'sell': SELL,
    'buy': BUY
}

EXCHANGE_INIT = 0
EXCHANGE_PENDING = 1
EXCHANGE_COMPLETED = 2

AVAILABLE_TASK_STATUS = {
    'init': EXCHANGE_INIT,
    'pending': EXCHANGE_PENDING,
    'completed': EXCHANGE_COMPLETED
}

CELERY_RETRY_COUNTDOWN = 0.1
CELERY_MAX_RETRIES = 1000

BTC = 0
ETH = 1
AVAILABLE_CURRENCIES = {
    'btc': BTC,
    'eth': ETH
}

MAX_DIGITS = 15
DECIMAL_PLACES = 8

OFFER_MAX_DIGITS = MAX_DIGITS + (MAX_DIGITS - DECIMAL_PLACES)
ACCOUNT_MAX_DIGITS = OFFER_MAX_DIGITS

USERNAME_LENGTH = 30

MARKET_INFO_DELTA = 24
MARKET_INFO_COUNT_OF_EXCHANGES = 10

TOPIC_MARKET_INFO = "marketinfo"

DEFAULT_AMOUNT = 0

AMOUNT_MIN_VALUE = 1
VIABLE_UNIT = 10 ** DECIMAL_PLACES
EXCHANGE_AMOUNT_MIN_VALUE = convert(0.001)
WEI_IN_ETH = 10 ** 18

PRICE_MIN_VALUE = 1 / VIABLE_UNIT
PRICE_MAX_VALUE = 5000
