import decimal

__author__ = 'andrew.shvv@gmail.com'

ORDER_INIT = 'init'
ORDER_PENDING = 'pending'
ORDER_APPROVING = 'approving'
ORDER_APPROVED = 'approved'
ORDER_CANCELED = 'canceled'
ORDER_COMPLETED = 'completed'
ORDER_LOCKED = 'locked'
AVAILABLE_ORDER_STATUSES = [
    ORDER_INIT,
    ORDER_PENDING,
    ORDER_APPROVING,
    ORDER_APPROVED,
    ORDER_CANCELED,
    ORDER_COMPLETED,
    ORDER_LOCKED
]

ORDER_SELL = 'sell'
ORDER_BUY = 'buy'
AVAILABLE_ORDER_TYPES = [
    ORDER_SELL,
    ORDER_BUY
]

PAIR_BTC_ETH = 'btc_eth'
AVAILABLE_CURRENCY_PAIRS = [
    PAIR_BTC_ETH
]

BTC = 'btc'
ETH = 'eth'
AVAILABLE_CURRENCIES = [
    BTC,
    ETH
]

CELERY_RETRY_COUNTDOWN = 0.1
CELERY_MAX_RETRIES = 1000

POLONIEX_OFFER_MODIFIED = "orderBookModify"
POLONIEX_OFFER_REMOVED = "orderBookRemove"

EPS = decimal.Decimal(1 / 10 ** 8)

ACCOUNT_POOL_LENGTH = 5

MAX_DIGITS = 17
DECIMAL_PLACES = 8

OFFER_MAX_DIGITS = MAX_DIGITS + (MAX_DIGITS - DECIMAL_PLACES)
ACCOUNT_MAX_DIGITS = OFFER_MAX_DIGITS

USERNAME_LENGTH = 30

MARKET_INFO_DELTA = 24
MARKET_INFO_COUNT_OF_EXCHANGES = 10

TOPIC_OFFERS = "offers_{pair}_{type}"
TOPIC_HISTORY = "history_{pair}_{type}"
TOPIC_MARKET_INFO = "marketinfo"

DEFAULT_AMOUNT = 0

WITHDRAW_AMOUNT_MIN_VALUE = decimal.Decimal(1 / 10 ** 3)
DEPOSIT_AMOUNT_MIN_VALUE = 0
PRICE_MIN_VALUE = decimal.Decimal(1 / 10 ** 8)
PRICE_MAX_VALUE = 5000
ORDER_MIN_TOTAL_AMOUNT = round(decimal.Decimal(0.001), 3)
WEI_IN_ETH = 10 ** 18

COINBASE_PAYMENT_NOTIFICATION = "wallet:addresses:new-payment"

ERROR_NOT_FOUND = 'not_found'
ERROR_INTERNAL = 'internal_server_error'
ERROR_PERMISSION_DENIED = 'permission_denied'
ERROR_NOT_ENOUGH_MONEY = 'not_enough_money'
ERROR_LOCK_FAILURE = 'lock_failure'
ERROR_UNLOCK_FAILURE = 'unlock_failure'
ERROR_UPDATE_FAILURE = 'update_failure'
ERROR_ALREADY_EXIST = 'already_exist'
ERROR_NOT_ALLOWED = 'not_allowed'
ERROR_VALIDATION = 'validation_error'
ERROR_AUTHENTICATION = 'authentication_error'
