# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=26),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='price',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='rate',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='rate_24h_max',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='rate_24h_min',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='volume_24h',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=26),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=19),
        ),
    ]
