# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeshistory',
            name='exchange_ptr',
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=22),
        ),
        migrations.DeleteModel(
            name='ExchangesHistory',
        ),
    ]
