# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('absortium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='pair',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
