# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0002_auto_20160413_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
