# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0002_auto_20160425_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='primary_currency',
            new_name='from_currency',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='secondary_currency',
            new_name='to_currency',
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set([('to_currency', 'from_currency', 'price')]),
        ),
    ]
