# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('absortium', '0002_auto_20160408_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='pair',
            field=models.IntegerField(choices=[(0, 'BTC_ETH'), (1, 'BTC_XMR')]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.IntegerField(choices=[(1, 'sell'), (2, 'buy')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.IntegerField(choices=[(0, 'BTC_ETH'), (1, 'BTC_XMR')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(1, 'sell'), (2, 'buy')]),
        ),
    ]
