# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0002_auto_20160620_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='system',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='system',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set([('to_currency', 'from_currency', 'price', 'system')]),
        ),
    ]
