# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0002_auto_20160517_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('created',)},
        ),
    ]
