# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0003_auto_20160522_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=15)),
                ('rate_24h_max', models.DecimalField(decimal_places=8, max_digits=15)),
                ('rate_24h_min', models.DecimalField(decimal_places=8, max_digits=15)),
                ('volume_24h', models.DecimalField(decimal_places=8, max_digits=15)),
                ('from_currency', models.IntegerField()),
                ('to_currency', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
