# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0003_auto_20160413_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=22),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
