# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0004_marketinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='marketinfo',
            options={'ordering': ('-created',)},
        ),
    ]
