# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0005_auto_20160602_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='volume_24h',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
