# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absortium', '0005_deposit_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='address',
            field=models.CharField(default='123123123123', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
